sudo: required
services:
  - docker

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip --version
  - docker --version
  - docker-compose --version

install:
  - pip install tox
  - pip install coveralls

before_script:
  - pip install --upgrade setuptools wheel
  - docker-compose -f tests/docker-compose.yml pull
  - docker-compose -f tests/docker-compose.yml build

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then tox -e py35; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then tox -e py36; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then tox -e py37; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then tox -e py38; fi

after_script:
  # Always leave a clean slate.
  - docker-compose -f tests/docker-compose.yml down

after_success:
  - coveralls
