sudo: required
services:
  - docker

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install --upgrade setuptools wheel
  - pip --version
  - docker --version
  - docker-compose --version

install:
  - pip install tox
  - pip install coveralls

before_script:
  # Pre-cache images to prevent timeout in service availability checks.
  - docker-compose -f tests/docker-compose.yml pull
  - docker-compose -f tests/docker-compose.yml build

script:
  - tox

after_script:
  # Always leave a clean slate.
  - docker-compose -f tests/docker-compose.yml down

after_success:
  - coveralls
